language: python

python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "pypy"

before_install:
  - git config --global user.email "you@example.com"
  - git config --global user.name "Your Name"

script: make test
